version: "3.3"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

     
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
      
  mbootcoin:
    build:
      context: .
    ports:
      - "8088:8088"
    depends_on:
      - "mproductdb"
    
  mbootcoindb:
    image: mongo:latest
    restart: always
    ports:
      - "2030:27017"
    volumes:
      - "../db:/data/db"
      
      
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
    
networks:
  default:
    name: netbank
    ipam:
      config:
        - subnet: 192.165.0.0/16